name: Deploy Website to GitHub Pages

on:
  release:
    types: [published, edited]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-website:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ljmng7/MacMix/.github/workflows/pages.yml@website
